### ISSUE TITLE
[compat] South Park

### ISSUE THREAD

**Issue by Rustydw** [hensm/fx_cast-compat#1]
**App name:** South Park
**App URL:**  [https://www.southparkstudios.com/](https://www.southparkstudios.com/)
**App ID (if possible):**

**Issues:**

**Error log (if applicable):**

**Comment by nettnikl** [comment]
> You didn't mention whether this is compatible.

I can confirm, that it is not possible.
May (how) people can help with testing?

**Comment by hensm** [comment]
@nettnikl

> May (how) people can help with testing?

If there are specific issues, describe them in detail (e.g. the cast button appears, but doesn't respond to clicks; when attempting to cast, the player hangs and never finishes connecting, etc...).

To fix these issues, I would usually debug the player and Chromecast sender application with the browser dev tools and step through the code to figure out where any incompatibilities are, but obviously I can't do that here.

**Comment by nettnikl** [comment]
> obviously I can't do that here

Could you explain why? Maybe i can do so, but i'm not sure where to start.

**Comment by hensm** [comment]
Geoblocking, as I mentioned in the initial response. It's not available in the UK.

If you want to try and debug it yourself, it's a little involved, but you'd have to first get a development version of the extension running and set some breakpoints in the page scripts for the South Park site where they're calling the Chromecast sender SDK APIs.

Depending on what's broken, you'd look in different places.

If there isn't a cast button showing up at all, you'd look at where the [sender SDK is loaded](https://developers.google.com/cast/docs/web_sender/integrate). They should be initializing cast stuff in the `window.__onGCastApiAvailable` callback, so you'd be able to follow it from there. Depending on whether they're using the newer [Cast Application Framework (CAF)](https://developers.google.com/cast/docs/web_sender), or the older [`chrome.cast`](https://developers.google.com/cast/docs/reference/web_sender/chrome.cast) base API, the cast button would either be a custom element (`<google-cast-launcher>`) handled by CAF or an element whose visibility is handled by the app in response to receiver listeners passed in the [`chrome.cast.ApiConfig`](https://developers.google.com/cast/docs/reference/web_sender/chrome.cast.ApiConfig) object when [initializing the API](https://developers.google.com/cast/docs/reference/web_sender/chrome.cast).

If there's some unexplainable behaviour like UI not updating or responding to session creation or updates, you'd need to find where that's supposed to be happening (CAF and the base API have different methods for registering listeners) and compare the behaviour to what happens in Chrome.

Could be that the extension is returning data that isn't what the app expects and causing script errors, or browser-specific code is causing errors in Firefox because of user agent sniffing. Might be unimplemented parts of the API or the way the bridge code is sending messages or handling responses from the Chromecast. Anything that behaves differently to Chrome could be a source of bugs.

Fair warning though, the page script code is usually minified/obfuscated and pretty annoying go through.

**Comment by nettnikl** [comment]
Oh wow, thanks for the detailed answer. Will see if i can figure it out, i'm very interested in getting this to work.

**Comment by nettnikl** [comment]
Alright, looking into this, i can see how pages are made compatible to chromecast. And it seems, i have misunderstood, how this project achieves it's features - i assumed, it would work with generic pages.

I think i misunderstood the following:
> A Firefox extension that implements the Chromecast API and exposes it to web apps to enable cast support

As the requested page seems not to contains any chrome cast related lib or scripts, i now doubt that this project is supporting this case - am i right?

**Comment by hensm** [comment]
Right, yes.

It provides an implementation of the sender SDK _if_ a site requests it. The site itself has to have a sender app that utilises it.

There's also support for basic HTML5 media (simply forwarding the URL), and experimental screen mirroring that isn't suitable for video streaming.

Chrome has some optimisations to more efficiently stream generic video content over a screen mirroring session, but that's not something this project supports or likely will ever be able to support.
